### ISSUE TITLE
README : "max_old_used_space" vs "max_old_space_size"

### ISSUE THREAD

**Issue by Macadoshis** [isaacplmann/angular-cli-alias#1]
Your README mentions `max_old_used_space`, but your script file seems to read `max_old_space_size`.

`max_old_used_space` is mentioned nowhere in your source file. How is it supposed to work ?

**Comment by isaacplmann** [comment]
The readme probably should be max_old_space_size.  Want to submit a PR to
fix that?

**Comment by Macadoshis** [comment]
In fact it happens to be correct on source file `README.MD@master`, but not on the release.
Project should have been released after the renaming : https://github.com/isaacplmann/angular-cli-alias/commit/441fe98fc855d2c4e15e8eb9a7b5c8b284c07938#diff-0730bb7c2e8f9ea2438b52e419dd86c9.
* https://github.com/isaacplmann/angular-cli-alias / README.MD => correct value `max_old_space_size` 
* https://www.npmjs.com/package/angular-cli-alias / README.MD => incorrect value `max_old_used_space`

If sticking to npm registry documentation only, people might set a value that will never have any effect.

Could you _npm deploy_ a new version please ?

**Comment by isaacplmann** [comment]
Thanks for the head up!  1.0.9 is now published.
